### ISSUE TITLE
Preserve the To Investigate status of the test case while updating with the prediction

### ISSUE THREAD

**Issue by jirimacku** [JunqiZhang0/tfacon#18]
It is necessary to preserve the 'To Investigate' status of the test case to differentiate between test cases which were already looked upon an those which are still waiting for it.
One good approach could be to introduce subtypes to the 'TO INVESTIGATE' group and update the test case to this subtypes according to the prediction. Not only the precious information about what still needs to be investigate remains preserved but also the predictions are nicely shown through out the whole Report portal. When the colors of the new subtypes are select to be similar to the actual defect types it makes the user experience even better.

**Comment by JunqiZhang0** [comment]
@jirimacku Thanks for bring this up, we had a discussion regarding this, we will have another discussion regarding ** preserve the 'To Investigate' status**, I'll keep you posted!

**Comment by JunqiZhang0** [comment]
An solution has been added, so close this issue for now
