### ISSUE TITLE
tfacon could not update all failed items in a test run with the right prediction & always retruns update failed.

### ISSUE THREAD

**Issue by kasturinarra** [JunqiZhang0/tfacon#22]
**Describe the bug**
When run tfacon run -v against Openshift RPV5, i see that out of three test items only one of them were updated with the prediction from TFA and tfacon script was always returning "Update Failed" and the script does not return back for about an hour.

**To Reproduce**
1. Browse through https://reportportal-openshift.apps.ocp4.prod.psi.redhat.com/ui/
2. Login as ocptester/ocptester
3. Get a launch id
4. Add all details to tfacon.yml
5. Run tfacon run -v

**Expected behavior**
All failed plus to investigate items should get update with the right prediction

**Screenshots**
![image](https://user-images.githubusercontent.com/7300331/134550383-b0678be5-ae82-4cca-9977-009cb0b55783.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Junqi zhang was able to reproduce this issue and is currently debugging the same.

Pasting logs here for reference:
==============================
2021/09/20 22:57:00 Getting prediction of test item(id): 366
2021/09/20 22:57:00 Updating All Test Items With Predictions...
Updated Failed!
2021/09/20 22:57:02 Updated the test item(id): 367 with it's prediction 
2021/09/20 22:57:02 Getting prediction of test item(id): 367
2021/09/20 22:57:02 Updated the test item(id): 370 with it's prediction Predicted Product Bug
2021/09/20 22:57:02 Getting prediction of test item(id): 370
2021/09/20 22:57:32 Updated the test item(id): 366 with it's prediction Predicted Automation Bug
panic: Put "https://reportportal-openshift.apps.ocp4.prod.psi.redhat.com/api/v1/OCPTRIAL1/item/366/update": EOF

goroutine 449 [running]:
github.com/JunqiZhang0/tfacon/connectors.(*RPConnector).BuildIssueItemHelper(0xc000076d20, 0xc0003a8012, 0x3, 0x6f1d01, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/knarra/automation/Openshift/goproj/pkg/mod/github.com/!junqi!zhang0/tfacon@v1.0.0/connectors/rp_connector.go:186 +0x4d7
github.com/JunqiZhang0/tfacon/connectors.(*RPConnector).BuildIssueItemConcurrent(0xc000076d20, 0xc00038e600, 0xc00038e6c0, 0xc0003901c0, 0xc0001ea001)
	/home/knarra/automation/Openshift/goproj/pkg/mod/github.com/!junqi!zhang0/tfacon@v1.0.0/connectors/rp_connector.go:199 +0x65
created by github.com/JunqiZhang0/tfacon/connectors.(*RPConnector).BuildIssuesConcurrent
	/home/knarra/automation/Openshift/goproj/pkg/mod/github.com/!junqi!zhang0/tfacon@v1.0.0/connectors/rp_connector.go:156 +0x15d

**Comment by JunqiZhang0** [comment]
@kasturinarra The problem has been solved, so close this issue

**Comment by kasturinarra** [comment]
@JunqiZhang0  thank you !!
